name: Validate CSV

on:
  push:
    paths:
      - 'data/**/*.csv'
      - 'src/**/*.py'
      - 'requirements.txt'
      - 'README.md'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Lint CSV schema (quick check)
        run: |
          python - <<'PY'
          import pandas as pd, sys
          ok = True
          required = {"term_a","term_b"}
          try:
              df = pd.read_csv("data/word_pairs.csv")
              if not required.issubset(df.columns):
                  print("Missing required columns in data/word_pairs.csv")
                  ok = False
          except Exception as e:
              print("CSV read error:", e)
              ok = False
          sys.exit(0 if ok else 1)
          PY
